# Site settings
title: J.Leoprogrammer
header-img: img/home-bg.png
email: jleopold424@gmail.com
copyright_name: Jenna424
description: > # this means to ignore newlines until "baseurl:"
  My Coding Projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jenna424
learn_profile: Jenna424
email_username: jleopold424@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
